global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'pg-wire-mock'
    static_configs:
      - targets: ['pg-wire-mock:9091']
    scrape_interval: 5s
    metrics_path: /metrics
