global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here if needed
  # - "alert_rules.yml"

scrape_configs:
  # Scrape PostgreSQL metrics from postgres_exporter
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Scrape pg-wire-mock metrics
  - job_name: 'pg-wire-mock'
    static_configs:
      - targets: ['pg-wire-mock:9091']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
